services:

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - 3000:3000/tcp
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: true
    volumes:
      - ./data/grafana/data:/var/lib/grafana
      - ./data/grafana/provisioning:/etc/grafana/provisioning

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: unless-stopped
    command:
      - --config.file
      - /etc/prometheus/prometheus.yaml
      - --storage.tsdb.path
      - /prometheus
    ports:
      - 9090:9090/tcp
    volumes:
      - ./data/prom/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./data/prom/data:/prometheus